export const controlsList = [
  { id: "email", name: "Email Form Control" },
  { id: "color", name: "Color Form Control" },
  { id: "date", name: "Date Form Control" },
  { id: "datetime-local", name: "Datetime-local Form Control" },
  { id: "month", name: "Month Form Control" },
  { id: "number", name: "Number Form Control" },
  { id: "password", name: "Password Form Control" },
  { id: "search", name: "Search Form Control" },
  { id: "tel", name: "Mobile Phone Number Form Control" },
  { id: "text", name: "Text Form Control" },
  { id: "time", name: "Time Form Control" },
  { id: "url", name: "Url Form Control" },
  { id: "week", name: "Week Form Control" },
  { id: "select", name: "Select Form Control" },
  { id: "radio", name: "Radio Form Control" },
  { id: "chips", name: "Chips Form Control" },
];

export const TypeControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Select Control Type",
  name: "type",
  value: "",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [...controlsList],
};
export const LabelControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  placeholder: "Enter Label form Controller",
  label: "Label for Controller",
  name: "label",
  type: "text",
};
export const NameControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  placeholder: "Enter Name for Controller",
  label: "Name for Controller",
  name: "name",
  type: "text",
};
export const ValueControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Default Value for Controller",
  label: "Default Value",
  name: "value",
  type: "text",
};
export const ColumnClassControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  label: "Column Class",
  name: "columnClass",
  type: "text",
};
export const ControllerClassControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  label: "Controller Class",
  name: "controllerClass",
  type: "text",
};
export const DataProviderControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Data Reference Table",
  name: "dataProviderCollectionName",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [],
};
export const IdentifyByControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  value: "id",
  oldValue: "id",
  placeholder: "Data Item Identify By",
  label: "Data Item Identify By",
  name: "identifyBy",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [],
};
export const DisplayByControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: true,
  value: "name",
  oldValue: "name",
  placeholder: "Data Item Display By",
  label: "Data Item Display By",
  name: "displayBy",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [],
};
export const FilterByControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  value: "",
  oldValue: "",
  placeholder: "Data Item Filter By",
  label: "Data Item Filter By",
  name: "filterBy",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [],
};
export const FilterValueControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  value: "",
  oldValue: "",
  placeholder: "Data Filter Value Control",
  label: "Data Filter Value Control",
  name: "filterValueControl",
  type: "select",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [],
};
export const RequiredControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Is Control Required",
  name: "required",
  value: true,
  type: "radio",
  multiple: true,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const HideControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Is Control Hide",
  name: "hide",
  value: false,
  type: "radio",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const AllowDuplicateControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Allow Duplicate Value",
  name: "duplicate",
  value: true,
  type: "radio",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const DisabledControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Is Control Disabled",
  name: "disabled",
  value: false,
  type: "radio",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const ShowInGridControl = {
  columnClass: "col-md-12 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "show Control In Grid",
  name: "showInGrid",
  value: true,
  type: "radio",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const MultipleControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  controllerClass: "w-100",
  disabled: false,
  required: true,
  label: "Allow Multi Selection",
  name: "multiple",
  value: false,
  type: "radio",
  multiple: false,
  identifyBy: "id",
  displayBy: "name",
  dataProvider: [
    {
      id: true,
      name: "Yes",
    },
    {
      id: false,
      name: "No",
    },
  ],
};
export const MinLengthControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Min Length Required",
  label: "Min Length for Validation",
  name: "minlength",
  type: "number",
};
export const MaxLengthControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Max Length Allowed",
  label: "Max Length for Validation",
  name: "maxlength",
  type: "number",
};
export const MinControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Min Value Required",
  label: "Min Value  for Validation",
  name: "min",
  type: "number",
};
export const MaxControl = {
  columnClass: "col-md-6 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Max Value Allowed",
  label: "Max Value for Validation",
  name: "max",
  type: "number",
};
export const PatternControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Allowed Pattern for Value",
  label: "Pattern for Validation",
  name: "pattern",
  type: "text",
};
export const PlaceHolderControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Place Holder",
  label: "Place Holder",
  name: "placeholder",
  type: "text",
};
export const RequiredErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Required Validation Error Message",
  label: "Required Validation Error Message",
  name: "requiredError",
  type: "text",
};
export const DuplicateErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Duplicate Validation Error Message",
  label: "Duplicate Validation Error Message",
  name: "duplicateErrorControl",
  type: "text",
};
export const EmailErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Email Validation Error Message",
  label: "Email Validation Error Message",
  name: "emailError",
  type: "text",
};
export const MinErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Min Validation Error Message",
  label: "Min Validation Error Message",
  name: "minError",
  type: "text",
};
export const MaxErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Max Validation Error Message",
  label: "Max Validation Error Message",
  name: "maxError",
  type: "text",
};
export const MinLengthErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Min Validation Error Message",
  label: "Min Length Validation Error Message",
  name: "minlengthError",
  type: "text",
};
export const MaxLengthErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Max Validation Error Message",
  label: "Max Length Validation Error Message",
  name: "maxlengthError",
  type: "text",
};
export const PatternErrorControl = {
  columnClass: "col-12 mb-1",
  hide: false,
  disabled: false,
  controllerClass: "w-100",
  required: false,
  placeholder: "Enter Pattern Validation Error Message",
  label: "Pattern Length Validation Error Message",
  name: "patternError",
  type: "text",
};

export enum EDIT_CONFIG {
  TYPE = 0,
  LABEL = 1,
  NAME = 2,
  VALUE = 3,
  COLUMN_CLASS = 4,
  CONTROLLER_CLASS = 5,
  DATA_PROVIDER = 6,
  IDENTIFY_BY = 7,
  DISPLAY_BY = 8,
  FILTER_BY = 9,
  FILTER_VALUE = 10,
  REQUIRED = 11,
  ALLOW_DUPLICATE = 12,
  HIDE = 13,
  DISABLED = 14,
  SHOW_IN_GRID = 15,
  MULTIPLE = 16,
  MIN_LENGTH = 17,
  MAX_LENGTH = 18,
  MIN = 19,
  MAX = 20,
  PATTERN = 21,
  PLACE_HOLDER = 22,
  REQUIRED_ERROR = 23,
  DUPLICATE_ERROR = 24,
  EMAIL_ERROR = 25,
  MIN_ERROR = 26,
  MAX_ERROR = 27,
  MIN_LENGTH_ERROR = 28,
  MAX_LENGTH_ERROR = 29,
  PATTERN_ERROR = 30,
}

export const FormControlsConfigList = [
  TypeControl,
  LabelControl,
  NameControl,
  ValueControl,
  ColumnClassControl,
  ControllerClassControl,
  DataProviderControl,
  IdentifyByControl,
  DisplayByControl,
  FilterByControl,
  FilterValueControl,
  RequiredControl,
  AllowDuplicateControl,
  HideControl,
  DisabledControl,
  ShowInGridControl,
  MultipleControl,
  MinLengthControl,
  MaxLengthControl,
  MinControl,
  MaxControl,
  PatternControl,
  PlaceHolderControl,
  RequiredErrorControl,
  DuplicateErrorControl,
  EmailErrorControl,
  MinErrorControl,
  MaxErrorControl,
  MinLengthErrorControl,
  MaxLengthErrorControl,
  PatternErrorControl,
];

export enum CONTROL_TYPE {
  EMAIL = "email",
  COLOR = "color",
  DATE = "date",
  DATETIME_local = "datetime-local",
  MONTH = "month",
  NUMBER = "number",
  PASSWORD = "password",
  SEARCH = "search",
  TEL = "tel",
  TEXT = "text",
  TIME = "time",
  URL = "url",
  WEEK = "week",
  SELECT = "select",
  RADIO = "radio",
  CHIPS = "chips",
}
