import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Home",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/dashboard/main",
        title: "Dashboard 1",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard2",
        title: "Dashboard 2",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Memberships",
    iconType: "material-icons-two-tone",
    icon: "airline_seat_individual_suite",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/memberships/all",
        title: "All Memberships",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Professors",
    iconType: "material-icons-two-tone",
    icon: "person",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/professors/all-professors",
        title: "All Professors",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/professors/add-professor",
        title: "Add Professor",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/professors/edit-professor",
        title: "Edit Professor",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/professors/about-professor",
        title: "About Professor",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Dynamic Forms",
    iconType: "material-icons-two-tone",
    icon: "tv",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/dynamic-forms",
        title: "Manage Dynamic Forms",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Online Classes",
    iconType: "material-icons-two-tone",
    icon: "tv",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/online-classes/start-online-classes",
        title: "Start Online Class",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/online-classes/manage-online-classes",
        title: "Manage Online Class",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/online-classes/join-online-classes",
        title: "Join Online Class",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Institutions",
    iconType: "material-icons-two-tone",
    icon: "business",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/institutions/all-institutions",
        title: "All Institutions",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/institutions/add-institution",
        title: "Add Institution",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Students",
    iconType: "material-icons-two-tone",
    icon: "people_alt",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/students/all-students",
        title: "All Students",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/students/add-student",
        title: "Add Students",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/students/edit-student",
        title: "Edit Students",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/students/about-student",
        title: "About Students",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Courses",
    iconType: "material-icons-two-tone",
    icon: "school",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/courses/all-courses",
        title: "All Courses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/courses/add-course",
        title: "Add Courses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/courses/edit-course",
        title: "Edit Courses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/courses/about-course",
        title: "About Courses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Library",
    iconType: "material-icons-two-tone",
    icon: "local_library",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/library/all-assets",
        title: "All Library Assets",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/library/add-asset",
        title: "Add Library Assets",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/library/edit-asset",
        title: "Edit Library Assets",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Departments",
    iconType: "material-icons-two-tone",
    icon: "business",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/departments/all-departments",
        title: "All Departments",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/departments/add-department",
        title: "Add Department",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/departments/edit-department",
        title: "Edit Department",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Staff",
    iconType: "material-icons-two-tone",
    icon: "face",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/staff/all-staff",
        title: "All Staff",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/staff/add-staff",
        title: "Add Staff",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/staff/edit-staff",
        title: "Edit Staff",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/staff/about-staff",
        title: "About Staff",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Holiday",
    iconType: "material-icons-two-tone",
    icon: "airline_seat_individual_suite",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/holidays/all-holidays",
        title: "All Holiday",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/holidays/add-holiday",
        title: "Add Holiday",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/holidays/edit-holiday",
        title: "Edit Holiday",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Fees",
    iconType: "material-icons-two-tone",
    icon: "monetization_on",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/fees/all-fees",
        title: "All Fees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/fees/add-fees",
        title: "Add Fees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/fees/edit-fees",
        title: "Edit Fees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/fees/fee-receipt",
        title: "Fees Receipt",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Email",
    iconType: "material-icons-two-tone",
    icon: "email",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/email/inbox",
        title: "Inbox",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/email/compose",
        title: "Compose",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/email/read-mail",
        title: "Read Email",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  /**/
  {
    path: "",
    title: "Apps",
    iconType: "material-icons-two-tone",
    icon: "stars",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/apps/calendar",
        title: "Calendar",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/apps/chat",
        title: "Chat",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/apps/dragdrop",
        title: "Drag & Drop",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/apps/contact-list",
        title: "Contact List",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/apps/contact-grid",
        title: "Contact Grid",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/apps/support",
        title: "Support",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Widgets",
    iconType: "material-icons-two-tone",
    icon: "widgets",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/widget/chart-widget",
        title: "Chart Widget",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/widget/data-widget",
        title: "Data Widget",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "User Interface (UI)",
    iconType: "material-icons-two-tone",
    icon: "dvr",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/ui/alerts",
        title: "Alerts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/animations",
        title: "Animations",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/badges",
        title: "Badges",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/chips",
        title: "Chips",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/modal",
        title: "Modal",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/buttons",
        title: "Buttons",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/expansion-panel",
        title: "Expansion Panel",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/bottom-sheet",
        title: "Bottom Sheet",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/dialogs",
        title: "Dialogs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/cards",
        title: "Cards",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/labels",
        title: "Labels",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/list-group",
        title: "List Group",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/media-object",
        title: "Media Object",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/snackbar",
        title: "Snackbar",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/preloaders",
        title: "Preloaders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/progressbars",
        title: "Progress Bars",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/tabs",
        title: "Tabs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/typography",
        title: "Typography",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/ui/helper-classes",
        title: "Helper Classes",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Forms",
    iconType: "material-icons-two-tone",
    icon: "subtitles",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/forms/form-controls",
        title: "Form Controls",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/forms/advance-controls",
        title: "Advanced Controls",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/forms/form-example",
        title: "Form Examples",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/forms/form-validation",
        title: "Form Validation",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/forms/wizard",
        title: "Form Wizard",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/forms/editors",
        title: "Editors",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Tables",
    iconType: "material-icons-two-tone",
    icon: "view_list",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/tables/basic-tables",
        title: "Basic Tables",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/tables/material-tables",
        title: "Material Tables",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/tables/ngx-datatable",
        title: "ngx-datatable",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Medias",
    iconType: "material-icons-two-tone",
    icon: "image_search",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/media/gallery",
        title: "Image Gallery",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/media/start-online-classes",
        title: "Carousel",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Charts",
    iconType: "material-icons-two-tone",
    icon: "insert_chart",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/charts/echart",
        title: "Echart",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/morris",
        title: "Morris",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/apex",
        title: "Apex",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/chartjs",
        title: "ChartJS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/ngx-charts",
        title: "Ngx-Charts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/gauge",
        title: "Gauge",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/charts/sparkline",
        title: "Sparkline",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Timeline",
    iconType: "material-icons-two-tone",
    icon: "timeline",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/timeline/timeline1",
        title: "Timeline 1",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/timeline/timeline2",
        title: "Timeline 2",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Icons",
    iconType: "material-icons-two-tone",
    icon: "eco",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/icons/material",
        title: "Material Icons",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/icons/font-awesome",
        title: "Font Awesome",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Authentication",
    iconType: "material-icons-two-tone",
    icon: "supervised_user_circle",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/authentication/signin",
        title: "Sign In",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/authentication/signup",
        title: "Sign Up",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/authentication/forgot-password",
        title: "Forgot Password",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/authentication/locked",
        title: "Locked",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/authentication/page404",
        title: "404 - Not Found",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/authentication/page500",
        title: "500 - Server Error",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Extra Pages",
    iconType: "material-icons-two-tone",
    icon: "description",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/extra-pages/profile",
        title: "Profile",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/extra-pages/pricing",
        title: "Pricing",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/extra-pages/invoice",
        title: "Invoice",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/extra-pages/faqs",
        title: "Faqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/extra-pages/blank",
        title: "Blank Page",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Maps",
    iconType: "material-icons-two-tone",
    icon: "map",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "/maps/google",
        title: "Google Map",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Multi level Menu",
    iconType: "material-icons-two-tone",
    icon: "slideshow",
    class: "menu-toggle",
    groupTitle: false,
    submenu: [
      {
        path: "#",
        title: "First",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "/",
        title: "Second",
        iconType: "",
        icon: "",
        class: "ml-sub-menu",
        groupTitle: false,
        submenu: [
          {
            path: "/",
            title: "Second 1",
            iconType: "",
            icon: "",
            class: "",
            groupTitle: false,
            submenu: [],
          },
          {
            path: "/",
            title: "Second 2",
            iconType: "",
            icon: "",
            class: "",
            groupTitle: false,
            submenu: [],
          },
        ],
      },
      {
        path: "#",
        title: "Third",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
];
